#ifndef VIBOFCHAIN_CHAINPARAMSSEEDS_H
#define VIBOFCHAIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the vibofchain network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x41,0x6d,0x8c,0x3d}, 2400},
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x87,0xb5,0xfb,0x01}, 2400}
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // VIBOFCHAIN_CHAINPARAMSSEEDS_H
